config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'homes#top'
  resources :posts,  only: [:index, :show, :create, :destroy] do
    resources :comments, only: [:create,:destroy]
  end
  resources :users do
    member do
      get :following, :followers , :likes
    end
  end
  resources :relationships,  only: [:create, :destroy]
  resources :messages, only:  [:create]
  resources :rooms, only: [:create, :show, :index]
  resources :notifications, only: [:index]
  resources :favorite_relationships, only: [:create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_error_messages.html.erb
<% if @post.errors.any? %>
<div id="error_explanation">
    <div class="alert alert-danger">
        入力ミスがあります
    </div>
    <ul>
        <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
</div>
<% end%>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
<ol class="posts">
    <%= render @feed_items %>
</ol>
<%= paginate @feed_items ,theme: 'twitter-bootstrap-4'%>
<% end %>

app/views/shared/_post_form.html.erb
<%= form_for(@post) do |f| %>
<%= render 'shared/error_messages', object: f.object %>
<h3>投稿する</h3>
<br>魚種
<br><%= f.text_field :fish, placeholder: "釣れた魚を入力" %>
<br>釣り場
<br><%= f.text_field :place, placeholder: "釣り場を入力" %>
<br>コメント
<br><%= f.text_area :content, placeholder: "コメントを入力" %>
<br><%= f.submit "投稿",  class: "btn btn-primary" %>
<span class="image">
    <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png" %>
</span>
<% end %>

<script type="text/javascript">
    $("#post_image").bind("change", function() {
        var size_in_megabytes = this.files[0].size / 1024 / 1024;
        if (size_in_megabytes > 5) {
            alert("Maximum file size is 5MB. Please choose a smaller file.");
            $("#post_image").val("");
        }
    });
</script>

app/views/shared/_posts_search_form.html.erb
<%= search_form_for @q, url: @url do |f| %>
  <%= f.label :fish_or_content_cont, '投稿内容検索' %>
  <div class="input-group">
    <%= f.text_field :fish_or_content_cont, placeholder: "投稿内容を入れてください",
                      class: 'form-control' %>
    <span class="input-group-btn">
     <%= f.submit '検索', class: "btn btn-primary" %>
    </span>
  </div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
    <a href="<%= following_user_path(@user) %>">
        <strong id="following" class="stat">
            <%= @user.following.count %>
        </strong>
        フォロー
    </a>
    <a href="<%= followers_user_path(@user) %>">
        <strong id="followers" class="stat">
            <%= @user.followers.count %>
        </strong>
        フォロワー
    </a>
    <a href="<%= likes_user_path(@user) %>">
        <strong id="likes" class="stat">
            <%= @user.likes.count %>
        </strong>
        いいね
    </a>
</div>