config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'homes#top'
  resources :posts,  only: [:index, :show, :create, :destroy] do
    resources :comments, only: [:create,:destroy]
  end
  resources :users do
    member do
      get :following, :followers , :likes
    end
  end
  resources :relationships,  only: [:create, :destroy]
  resources :messages, only:  [:create]
  resources :rooms, only: [:create, :show, :index]
  resources :notifications, only: [:index]
  resources :favorite_relationships, only: [:create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_one_attached :image
  has_many :notifications, dependent: :destroy
  has_many :favorite_relationships, dependent: :destroy
  has_many :liked_by, through: :favorite_relationships, source: :user
  validates :fish, presence: true
  validates :place, presence: true
  validates :image,   content_type: { in: %w[image/jpeg image/gif image/png],
    message: "must be a valid image format" },
size:         { less_than: 5.megabytes,
    message: "should be less than 5MB" }

  def create_notification_like!(current_user)
    # すでに「いいね」されているか検索
    temp = Notification.where(["visitor_id = ? and visited_id = ? and post_id = ? and action = ? ", current_user.id, user_id, id, 'like'])
    # いいねされていない場合のみ、通知レコードを作成
    if temp.blank?
      notification = current_user.active_notifications.new(
        post_id: id,
        visited_id: user_id,
        action: 'like'
      )
      # 自分の投稿に対するいいねの場合は、通知済みとする
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  def create_notification_comment!(current_user, comment_id)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    temp_ids = Comment.select(:user_id).where(post_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, comment_id, visited_id)
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    notification = current_user.active_notifications.new(
      post_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end

  def display_image
    image.variant(resize_to_limit: [500, 500])
  end

 
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
 before_action :authenticate_user!, only: [:create, :show, :destroy]
 before_action :correct_user, only: :destroy

 def index
  @post = Post.all.order(created_at: :desc)
 end

 def show
  @post = Post.find(params[:id])
  @comments = @post.comments
  @comment = Comment.new
 end

 def create
  @post = current_user.posts.build(post_params)
  @post.image.attach(params[:post][:image])
  if @post.save
    flash[:primary] = "投稿を作成しました"
    redirect_to root_url 
  else
    @q = Post.none.ransack
    @feed_items = current_user.feed.page(page: params[:page])
    render 'homes/top'  
  end
 end

 def destroy
    @post.destroy 
    flash[:primary] = "投稿を削除しました"
    redirect_to request.referrer || root_url
 end


 private
   def post_params
     params.require(:post).permit(:fish, :place, :content, :image)
   end

   

   def correct_user
     @post = current_user.posts.find_by(id: params[:id])
     redirect_to root_url if @post.nil?  
   end
 
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_like.html.erb
<%= form_for(current_user.favorite_relationships.build) do |f| %>
<div><%= hidden_field_tag :post_id, post.id %></div>
<%= button_tag(class: "btn btn-default" ) do %>
<i class="far fa-heart"></i>
<%= content_tag :span, post.liked_by.count %>
<% end %>
<% end %>

app/views/posts/_like_form.html.erb
<%= form_for(current_user.favorite_relationships.build, remote: true) do |f| %>

app/views/posts/_post.html.erb
<li>
    <span class="user">ユーザー名：<%= link_to post.user.name, post.user %></span>
    <span class="fish">魚種：<%= post.fish%></span>
    <span class="place">釣り場：<%= post.place%></span>
    <span class="content">ひとこと：<%= post.content%>
        <%= image_tag post.display_image if post.image.attached? %>
    </span>
    <span class="delete">
        <% if current_user?(post.user) %>
        <%= link_to "削除", post, method: :delete,
                                       data: { confirm: "本当に削除しますか？" } %>

        <% end %>
    </span>
    <span class="like" id="like_form_<%= post.id %>">
        <% if post.liked_by.include?(current_user) %>
        <%= render "posts/unlike", post: post %>
        <% else %>
        <%= render "posts/like", post: post %>
        <% end %>
    </span>
</li>

app/views/posts/_unlike.html.erb
<%= form_for(current_user.favorite_relationships.find_by(post_id: post.id),
             html: { method: :delete }) do |f| %>
<%= button_tag( class: "btn btn-default") do %>
<i class="far fa-heart"></i>
<%= content_tag :span, post.liked_by.count %>
<% end %>
<% end %>

app/views/posts/_unlike_form.html.erb
<%= form_for(current_user.favorite_relationships.find_by(post_id: post.id),
             html: { method: :delete }, remote: true) do |f| %>

app/views/posts/index.html.erb
<h2>投稿一覧</h2>

<ol class="posts">
    <% @post.each do |post|%>
    <li>
        <span class="user">ユーザー名：<%= link_to post.user.name, post.user %></span>
        <span class="fish">魚種：<%= post.fish%></span>
        <span class="place">釣り場：<%= post.place%></span>
        <span class="content">ひとこと：<%= post.content%>
            <%= image_tag post.display_image if post.image.attached? %>
        </span>
        <%= link_to '詳細をみる',  post_path(post) %>
    </li>
    <% end %>
</ol>

app/views/posts/show.html.erb
<h1>投稿詳細ページ</h1>
<li><%= @post.fish%></li>
<li><%= @post.place%></li>
<li><%= @post.content%></li>

<h2>コメント一覧</h2>
<% @post.comments.each do |comment| %>
<li>
    <%= comment.content %>
    <%= link_to "削除", post_comment_path(@post, comment), method: :delete,
                                       data: { confirm: "本当に削除しますか？" } %>
    <hr>
</li>
<% end %>

<%= form_for([@post, @post.comments.build]) do |f| %>
コメントを書く
<br><%= f.text_field :content %>
<br>
<%= f.submit 'コメントする' %>
<% end %>

<%= link_to "投稿一覧に戻る", posts_path %>