config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'homes#top'
  resources :posts,  only: [:index, :show, :create, :destroy] do
    resources :comments, only: [:create,:destroy]
  end
  resources :users do
    member do
      get :following, :followers , :likes
    end
  end
  resources :relationships,  only: [:create, :destroy]
  resources :messages, only:  [:create]
  resources :rooms, only: [:create, :show, :index]
  resources :notifications, only: [:index]
  resources :favorite_relationships, only: [:create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer fixed-bottom bg-secondary">
    <p>Copyright © 2020 Turiconnect app. All Rights Reserved.</p>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top bg-light">
    <div class="container">
        <%= link_to "釣りコネクト", root_path, id: "logo" %>
        <nav>
            <ul class="nav navbar-right">
                <li><%= link_to "ホーム", root_path %></li>
                <% if signed_in? %>
                <% if unchecked_notifications.any? %>
                <i class="fa fa-circle" style="color: gold;"></i>
                <% end %>
                <li><%= link_to "通知一覧", notifications_path, class: "btn-default" %></li>
                <li><%= link_to "投稿一覧", posts_path %></li>
                <li><%= link_to "アカウント編集",  edit_user_registration_path %></li>
                <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
                <% else %>
                <li><%= link_to "ログイン", new_user_session_path %></li>
                <li><%= link_to "新規登録", new_user_registration_path %></li>
                <% end %>
            </ul>
        </nav>
    </div>
</header>

app/views/layouts/_rails_default.html.erb
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
</head>

<body>
    <%= render 'layouts/header' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container">
        <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
        <%= yield %>
        <%= render 'layouts/footer' %>
    </div>
</body>

</html>